# generated by mBlock5 for <product>
# codes make you happy

import codey, event, neurons, time, rocky
# initialize variables
a = 0
codey.wifi.start('Maker-guest', 'makeblock')
# @event.button_c_pressed
# def on_button_c_pressed():
#     global a
#     while True:
#       codey.speaker.volume = (50)
#       codey.speaker.play_melody('hello.wav')

@event.start
def on_start():
    global a
    while True:
        if neurons.pir_sensor.is_activated(1):
            neurons.led_panel.show_image([0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0,0,0,1,1,1,1,0,0,0,0,0,1,1], 0, 1)
            time.sleep(1)
            neurons.led_panel.clear()
        codey.set_variable('a', 2)

@event.button_a_pressed
def on_button_a_pressed1():
    global a
    codey.speaker.volume = (50)
    codey.speaker.play_melody('hello.wav')

# @event.start
# def on_start1():
#     global a
#     while True:
#         if neurons.pir_sensor.is_activated(1):
#             neurons.led_panel.show_image([0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0,0,0,1,1,1,1,0,0,0,0,0,1,1], 0, 1)
#             time.sleep(1)
#             neurons.led_panel.clear()

#         rocky.forward(50, 1)

# @event.start
# def on_start2():
#     global a
#     while True:
#         neurons.servo_driver.set_angle(90, 0, 1)

